modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "${issues}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Furq"
description = "${description}"
logoFile = "assets/${id}/icon.png"

[["dependencies.${id}"]]
modId = "${loader}"
type = "required"
versionRange = "[${forgeConstraint}"
ordering = "NONE"
side = "CLIENT"

[["dependencies.${id}"]]
modId = "minecraft"
type = "required"
versionRange = "${mcdep}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "${id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"